const PDFDocument = require('pdfkit');
const { prisma } = require('../../config/database');

/**
 * Generate a PDF shortlist report for a JD
 * @param {string} jdId
 * @param {string} tenantId
 * @returns {Promise<{buffer: Buffer, filename: string}>}
 */
async function generatePdfReport(jdId, tenantId) {
  const jd = await prisma.jobDescription.findFirst({
    where: { id: jdId, tenantId },
  });
  if (!jd) throw new Error('Job description not found');

  const scores = await prisma.scoreRecord.findMany({
    where: { jdId, candidate: { tenantId, deletedAt: null } },
    include: {
      candidate: { select: { name: true, email: true, parsedData: true } },
    },
    orderBy: { totalScore: 'desc' },
    take: 50,
    distinct: ['candidateId'],
  });

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => {
      const buffer = Buffer.concat(chunks);
      const safeName = (jd.title || 'report').replace(/[^a-zA-Z0-9]/g, '_');
      resolve({
        buffer,
        filename: `RecruitIQ_Report_${safeName}_${new Date().toISOString().split('T')[0]}.pdf`,
      });
    });
    doc.on('error', reject);

    // Header
    doc.fontSize(24).fillColor('#3b82f6').text('RecruitIQ', { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(16).fillColor('#333').text('Candidate Shortlist Report', { align: 'center' });
    doc.moveDown(0.3);
    doc.fontSize(11).fillColor('#666').text(`Job: ${jd.title || 'Untitled'}`, { align: 'center' });
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, { align: 'center' });
    doc.text(`Total Candidates: ${scores.length}`, { align: 'center' });
    doc.moveDown(1);

    // Line separator
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#ddd').stroke();
    doc.moveDown(1);

    // Candidate list
    scores.forEach((score, index) => {
      if (doc.y > 700) doc.addPage();

      const dims = score.dimensionScores || {};
      const name = score.candidate.name || 'Unknown';

      doc.fontSize(13).fillColor('#1e293b').text(`${index + 1}. ${name}`, { continued: true });
      doc.fontSize(13).fillColor('#3b82f6').text(`  ${score.totalScore}/100`, { align: 'right' });

      doc.fontSize(9).fillColor('#666');
      doc.text(`Email: ${score.candidate.email || 'N/A'}  |  Skills: ${dims.skills ?? '-'}  |  Experience: ${dims.experience ?? '-'}  |  Education: ${dims.education ?? '-'}  |  Profile: ${dims.profile ?? '-'}`);

      if (score.explanation) {
        doc.fontSize(9).fillColor('#555').text(score.explanation.substring(0, 200) + (score.explanation.length > 200 ? '...' : ''));
      }

      doc.moveDown(0.8);
    });

    // Footer
    doc.fontSize(8).fillColor('#999').text('Generated by RecruitIQ — AI-Powered Resume Screening', 50, doc.page.height - 40, { align: 'center' });

    doc.end();
  });
}

/**
 * Generate a single-candidate PDF summary
 * @param {string} candidateId
 * @param {string} jdId
 * @param {string} tenantId
 * @returns {Promise<{buffer: Buffer, filename: string}>}
 */
async function generateCandidatePdf(candidateId, jdId, tenantId) {
  const candidate = await prisma.candidate.findFirst({
    where: { id: candidateId, tenantId, deletedAt: null },
  });
  if (!candidate) throw new Error('Candidate not found');

  const score = await prisma.scoreRecord.findFirst({
    where: { candidateId, jdId },
    orderBy: { scoredAt: 'desc' },
  });

  const jd = await prisma.jobDescription.findFirst({
    where: { id: jdId, tenantId },
    select: { title: true },
  });

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => {
      const safeName = (candidate.name || 'candidate').replace(/[^a-zA-Z0-9]/g, '_');
      resolve({
        buffer: Buffer.concat(chunks),
        filename: `RecruitIQ_${safeName}_Summary.pdf`,
      });
    });
    doc.on('error', reject);

    const parsed = candidate.parsedData || {};
    const dims = score?.dimensionScores || {};

    // Header
    doc.fontSize(22).fillColor('#3b82f6').text('RecruitIQ', { align: 'right' });
    doc.moveDown(0.5);
    doc.fontSize(20).fillColor('#1e293b').text(candidate.name || 'Unknown Candidate');
    doc.fontSize(11).fillColor('#666');
    if (candidate.email) doc.text(candidate.email);
    if (candidate.phone) doc.text(candidate.phone);
    if (parsed.location) doc.text(parsed.location);
    doc.moveDown(1);

    // Score section
    if (score) {
      doc.fontSize(14).fillColor('#1e293b').text(`Match Score: ${score.totalScore}/100`, { underline: true });
      doc.moveDown(0.5);

      doc.fontSize(10).fillColor('#333');
      doc.text(`Skills: ${dims.skills ?? 'N/A'}/100  |  Experience: ${dims.experience ?? 'N/A'}/100  |  Education: ${dims.education ?? 'N/A'}/100  |  Profile: ${dims.profile ?? 'N/A'}/100`);
      doc.moveDown(0.5);

      if (jd) doc.fontSize(9).fillColor('#666').text(`Scored against: ${jd.title}`);
      doc.moveDown(1);

      if (score.explanation) {
        doc.fontSize(12).fillColor('#1e293b').text('Assessment', { underline: true });
        doc.moveDown(0.3);
        doc.fontSize(10).fillColor('#444').text(score.explanation);
        doc.moveDown(1);
      }
    }

    // Experience
    if (parsed.work_experience?.length > 0) {
      doc.fontSize(12).fillColor('#1e293b').text('Work Experience', { underline: true });
      doc.moveDown(0.3);
      parsed.work_experience.slice(0, 5).forEach((exp) => {
        doc.fontSize(10).fillColor('#333').text(`${exp.title || 'Role'} at ${exp.company || 'Company'}`);
        doc.fontSize(9).fillColor('#666').text(`${exp.start_date || ''} — ${exp.end_date || 'Present'}`);
        if (exp.responsibilities?.length > 0) {
          exp.responsibilities.slice(0, 3).forEach((r) => {
            doc.fontSize(9).fillColor('#555').text(`  • ${r}`);
          });
        }
        doc.moveDown(0.5);
      });
      doc.moveDown(0.5);
    }

    // Education
    if (parsed.education?.length > 0) {
      doc.fontSize(12).fillColor('#1e293b').text('Education', { underline: true });
      doc.moveDown(0.3);
      parsed.education.forEach((edu) => {
        doc.fontSize(10).fillColor('#333').text(`${edu.degree || ''} ${edu.field || ''}`);
        doc.fontSize(9).fillColor('#666').text(`${edu.institution || ''} ${edu.year ? `(${edu.year})` : ''}`);
        doc.moveDown(0.3);
      });
      doc.moveDown(0.5);
    }

    // Skills
    if (parsed.skills?.length > 0) {
      doc.fontSize(12).fillColor('#1e293b').text('Skills', { underline: true });
      doc.moveDown(0.3);
      doc.fontSize(10).fillColor('#444').text(parsed.skills.join('  •  '));
    }

    // Footer
    doc.fontSize(8).fillColor('#999').text('Generated by RecruitIQ', 50, doc.page.height - 40, { align: 'center' });

    doc.end();
  });
}

module.exports = { generatePdfReport, generateCandidatePdf };
